### ISSUE TITLE
 read_userdata( $user_email) sounds like it wil expose data to third parties

### ISSUE THREAD

**Issue by mnelson4** [GDPRWP/standard#6]
It sounds like the plan is for a user to visit a page, enter their email, and then this function (
read_userdata( $user_email)) will be called and return all their data. Right?
The only trouble with this is that other people are likely to know a users email. Eg I know my friends email, but that shouldn’t give me access to all their usage data.
What do you think is the solution to this issue? Is it just that users will somehow need to confirm their own that email address? (Eg, we’ll send an email to that address with a link in it, and that link is where 
read_userdata( $user_email) will get called?)

**Comment by ePascalC** [comment]
I think the function is there to indicate something is needed for the data portability. The details (so from where it can and should be called) still need to be defined, but indeed it should not be just open to the frontend open for anybody to check.

**Comment by vyskoczilova** [comment]
I think sending the email would be strong enough (I mean, regarding basic data stored in WordPress - mainly WooCommerce and such style data (which you have to keep anyway because of billing, right). I would check double opt-in, or user is logged in (I mean - just to have it in your profile for one click) and somehow let the developer integrate it freely, eg:
1) in woo store - you are logged in and you can access the data
2) forms, selling-sites etc. without logging - you add your email and get verification

the good thing is that to be "logged in" can be super easily hardened (double verification etc.) so I would love to implement the final solution based on the data stored (as the website developer)

**Comment by mnelson4** [comment]
ya, if a user's logged in, it's easy to verify they own the email address. If they're not logged in, sending an email message to the email address, and having them click on the link, would be another way to verify they're the owner of that email address.
As far as implementation, I think it would make sense if this plugin added a shortcode (or Gutenberg block, if you're hip) which would:
* if the user isn't logged in, provide a link to log in or a form for them to enter their email address. When they submit the form, an email is sent to that email address with a link, and when they click it they return to this page with a query parameter that indicates their email address has been verified, and we then set a "email verified" cookie
* if the user is logged in, or they have the "email verified" cookie, we show the user's data, and provide links to download it and anonymyze it
Is something like that what other people were thinking?

**Comment by dejliglama** [comment]
@mnelson4 and @vyskoczilova you are absolutely right. The function itself isn't concerned with where and who can call it, but there should, of course, be some check in place, to verify who requests data. 

We're going to release a plugin that put one such search field available in the admin area of WordPress. But there isn't anything stopping you from putting this onto a user front-end.

**Comment by mnelson4** [comment]
ah cool. Well I think my concerns have been addressed, thanks

**Comment by mnelson4** [comment]
actually @dejliglama can you point me to this plugin you're working on? I may be able to help out with it
